---
title: "Tidytuesday 2020 week 3"
author: "Sea"
date: "1/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

```

```{r}
passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv')
```

```{r}
passwords %>%
  view()

```

How does password category relate to password strength?

```{r}
passwords %>%
  group_by(category) %>%
  summarise(mean = mean(strength))

passwords %>%
  filter(strength > 45)

```

```{r}
passwords %>%
  filter(!is.na(category)) %>%
  ggplot(aes(category, strength)) + geom_boxplot(aes(fill = category), show.legend = FALSE) + theme_minimal() + coord_flip() + scale_fill_brewer(type = "qual", palette = 8) + labs(x = "Password Categories", y = "Password Strength", title =  "Password Category VS Strength") + geom_text(aes(y = 47, x = "nerdy-pop"), label = "rush2112", nudge_x = -0.5) + geom_point(aes(x = "nerdy-pop", y = 48), color = "red", size = 5)
```

```{r}
ggsave("password.jpeg")

```

















